#!/etc/bin/env bash

# Bookmarked directories
export NNN_BMS="s:$SRC_HOME;v:$VM_SHARE;c:$XDG_CONFIG_HOME"

# Themes
# Nord scheme
BLK="0B" CHR="0B" DIR="04" EXE="06" REG="00" HARDLINK="06" SYMLINK="06" MISSING="00" \
ORPHAN="09" FIFO="06" SOCK="0B" OTHER="06"
# Onedark scheme
# BLK="04" CHR="04" DIR="04" EXE="00" REG="00" HARDLINK="00" SYMLINK="06" MISSING="00" \
# ORPHAN="01" FIFO="0F" SOCK="0F" OTHER="02"
export NNN_FCOLORS="$BLK$CHR$DIR$EXE$REG$HARDLINK$SYMLINK$MISSING$ORPHAN$FIFO$SOCK$OTHER"

# Plugins
NNN_PLUG='u:getplugs;d:dragdrop;p:preview-tui;e:suedit'
# Trash (needs trash-cli) instead of delete
export NNN_TRASH=1
# Show dotfiles on top
export LC_COLLATE="C" 
# Define FIFO (plugin requirement)
NNN_FIFO=/tmp/nnn.fifo